// source: SP/Rpc/Messaging/admin_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var SP_Rpc_Messaging_messaging_message_pb = require('../../../SP/Rpc/Messaging/messaging_message_pb.js');
goog.object.extend(proto, SP_Rpc_Messaging_messaging_message_pb);
goog.exportSymbol('proto.sp.rpc.messaging.AdminSendMessageRequest', null, global);
goog.exportSymbol('proto.sp.rpc.messaging.AdminSendMessageResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sp.rpc.messaging.AdminSendMessageRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sp.rpc.messaging.AdminSendMessageRequest.repeatedFields_, null);
};
goog.inherits(proto.sp.rpc.messaging.AdminSendMessageRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sp.rpc.messaging.AdminSendMessageRequest.displayName = 'proto.sp.rpc.messaging.AdminSendMessageRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sp.rpc.messaging.AdminSendMessageResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sp.rpc.messaging.AdminSendMessageResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sp.rpc.messaging.AdminSendMessageResponse.displayName = 'proto.sp.rpc.messaging.AdminSendMessageResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.sp.rpc.messaging.AdminSendMessageRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sp.rpc.messaging.AdminSendMessageRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    messageBox: jspb.Message.getFieldWithDefault(msg, 1, ""),
    id: jspb.Message.getFieldWithDefault(msg, 2, ""),
    sender: (f = msg.getSender()) && SP_Rpc_Messaging_messaging_message_pb.Message.Sender.toObject(includeInstance, f),
    receiverId: jspb.Message.getFieldWithDefault(msg, 4, "0"),
    content: (f = msg.getContent()) && SP_Rpc_Messaging_messaging_message_pb.Message.Content.toObject(includeInstance, f),
    senderTagsList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sp.rpc.messaging.AdminSendMessageRequest}
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sp.rpc.messaging.AdminSendMessageRequest;
  return proto.sp.rpc.messaging.AdminSendMessageRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sp.rpc.messaging.AdminSendMessageRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sp.rpc.messaging.AdminSendMessageRequest}
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessageBox(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 3:
      var value = new SP_Rpc_Messaging_messaging_message_pb.Message.Sender;
      reader.readMessage(value,SP_Rpc_Messaging_messaging_message_pb.Message.Sender.deserializeBinaryFromReader);
      msg.setSender(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readUint64String());
      msg.setReceiverId(value);
      break;
    case 5:
      var value = new SP_Rpc_Messaging_messaging_message_pb.Message.Content;
      reader.readMessage(value,SP_Rpc_Messaging_messaging_message_pb.Message.Content.deserializeBinaryFromReader);
      msg.setContent(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.addSenderTags(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sp.rpc.messaging.AdminSendMessageRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sp.rpc.messaging.AdminSendMessageRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessageBox();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSender();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      SP_Rpc_Messaging_messaging_message_pb.Message.Sender.serializeBinaryToWriter
    );
  }
  f = message.getReceiverId();
  if (parseInt(f, 10) !== 0) {
    writer.writeUint64String(
      4,
      f
    );
  }
  f = message.getContent();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      SP_Rpc_Messaging_messaging_message_pb.Message.Content.serializeBinaryToWriter
    );
  }
  f = message.getSenderTagsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      6,
      f
    );
  }
};


/**
 * optional string message_box = 1;
 * @return {string}
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.prototype.getMessageBox = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.sp.rpc.messaging.AdminSendMessageRequest} returns this
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.prototype.setMessageBox = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string id = 2;
 * @return {string}
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.sp.rpc.messaging.AdminSendMessageRequest} returns this
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Message.Sender sender = 3;
 * @return {?proto.sp.rpc.messaging.Message.Sender}
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.prototype.getSender = function() {
  return /** @type{?proto.sp.rpc.messaging.Message.Sender} */ (
    jspb.Message.getWrapperField(this, SP_Rpc_Messaging_messaging_message_pb.Message.Sender, 3));
};


/**
 * @param {?proto.sp.rpc.messaging.Message.Sender|undefined} value
 * @return {!proto.sp.rpc.messaging.AdminSendMessageRequest} returns this
*/
proto.sp.rpc.messaging.AdminSendMessageRequest.prototype.setSender = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sp.rpc.messaging.AdminSendMessageRequest} returns this
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.prototype.clearSender = function() {
  return this.setSender(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.prototype.hasSender = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional uint64 receiver_id = 4;
 * @return {string}
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.prototype.getReceiverId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, "0"));
};


/**
 * @param {string} value
 * @return {!proto.sp.rpc.messaging.AdminSendMessageRequest} returns this
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.prototype.setReceiverId = function(value) {
  return jspb.Message.setProto3StringIntField(this, 4, value);
};


/**
 * optional Message.Content content = 5;
 * @return {?proto.sp.rpc.messaging.Message.Content}
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.prototype.getContent = function() {
  return /** @type{?proto.sp.rpc.messaging.Message.Content} */ (
    jspb.Message.getWrapperField(this, SP_Rpc_Messaging_messaging_message_pb.Message.Content, 5));
};


/**
 * @param {?proto.sp.rpc.messaging.Message.Content|undefined} value
 * @return {!proto.sp.rpc.messaging.AdminSendMessageRequest} returns this
*/
proto.sp.rpc.messaging.AdminSendMessageRequest.prototype.setContent = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sp.rpc.messaging.AdminSendMessageRequest} returns this
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.prototype.clearContent = function() {
  return this.setContent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.prototype.hasContent = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * repeated string sender_tags = 6;
 * @return {!Array<string>}
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.prototype.getSenderTagsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.sp.rpc.messaging.AdminSendMessageRequest} returns this
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.prototype.setSenderTagsList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.sp.rpc.messaging.AdminSendMessageRequest} returns this
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.prototype.addSenderTags = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sp.rpc.messaging.AdminSendMessageRequest} returns this
 */
proto.sp.rpc.messaging.AdminSendMessageRequest.prototype.clearSenderTagsList = function() {
  return this.setSenderTagsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sp.rpc.messaging.AdminSendMessageResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.sp.rpc.messaging.AdminSendMessageResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sp.rpc.messaging.AdminSendMessageResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sp.rpc.messaging.AdminSendMessageResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sp.rpc.messaging.AdminSendMessageResponse}
 */
proto.sp.rpc.messaging.AdminSendMessageResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sp.rpc.messaging.AdminSendMessageResponse;
  return proto.sp.rpc.messaging.AdminSendMessageResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sp.rpc.messaging.AdminSendMessageResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sp.rpc.messaging.AdminSendMessageResponse}
 */
proto.sp.rpc.messaging.AdminSendMessageResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sp.rpc.messaging.AdminSendMessageResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sp.rpc.messaging.AdminSendMessageResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sp.rpc.messaging.AdminSendMessageResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sp.rpc.messaging.AdminSendMessageResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


goog.object.extend(exports, proto.sp.rpc.messaging);
