import { PaletteMode } from '@mui/material';
import { RenderOptions, RenderResult } from '@testing-library/react';
import { default as React } from '../../node_modules/react';
export type TestRouter = "router" | "memory";
interface CustomRenderOptions {
    renderOptions?: RenderOptions;
    mode?: PaletteMode;
    router?: TestRouter;
}
declare const customRender: (ui: React.ReactElement, options?: CustomRenderOptions) => RenderResult;
declare const customFireEvent: {
    type: (element: HTMLElement, value: string | number) => void;
    copy: (element: Document | Element | Window | Node, options?: {}) => boolean;
    cut: (element: Document | Element | Window | Node, options?: {}) => boolean;
    paste: (element: Document | Element | Window | Node, options?: {}) => boolean;
    compositionEnd: (element: Document | Element | Window | Node, options?: {}) => boolean;
    compositionStart: (element: Document | Element | Window | Node, options?: {}) => boolean;
    compositionUpdate: (element: Document | Element | Window | Node, options?: {}) => boolean;
    keyDown: (element: Document | Element | Window | Node, options?: {}) => boolean;
    keyPress: (element: Document | Element | Window | Node, options?: {}) => boolean;
    keyUp: (element: Document | Element | Window | Node, options?: {}) => boolean;
    focus: (element: Document | Element | Window | Node, options?: {}) => boolean;
    blur: (element: Document | Element | Window | Node, options?: {}) => boolean;
    focusIn: (element: Document | Element | Window | Node, options?: {}) => boolean;
    focusOut: (element: Document | Element | Window | Node, options?: {}) => boolean;
    change: (element: Document | Element | Window | Node, options?: {}) => boolean;
    input: (element: Document | Element | Window | Node, options?: {}) => boolean;
    invalid: (element: Document | Element | Window | Node, options?: {}) => boolean;
    submit: (element: Document | Element | Window | Node, options?: {}) => boolean;
    reset: (element: Document | Element | Window | Node, options?: {}) => boolean;
    click: (element: Document | Element | Window | Node, options?: {}) => boolean;
    contextMenu: (element: Document | Element | Window | Node, options?: {}) => boolean;
    dblClick: (element: Document | Element | Window | Node, options?: {}) => boolean;
    drag: (element: Document | Element | Window | Node, options?: {}) => boolean;
    dragEnd: (element: Document | Element | Window | Node, options?: {}) => boolean;
    dragEnter: (element: Document | Element | Window | Node, options?: {}) => boolean;
    dragExit: (element: Document | Element | Window | Node, options?: {}) => boolean;
    dragLeave: (element: Document | Element | Window | Node, options?: {}) => boolean;
    dragOver: (element: Document | Element | Window | Node, options?: {}) => boolean;
    dragStart: (element: Document | Element | Window | Node, options?: {}) => boolean;
    drop: (element: Document | Element | Window | Node, options?: {}) => boolean;
    mouseDown: (element: Document | Element | Window | Node, options?: {}) => boolean;
    mouseEnter: (element: Document | Element | Window | Node, options?: {}) => boolean;
    mouseLeave: (element: Document | Element | Window | Node, options?: {}) => boolean;
    mouseMove: (element: Document | Element | Window | Node, options?: {}) => boolean;
    mouseOut: (element: Document | Element | Window | Node, options?: {}) => boolean;
    mouseOver: (element: Document | Element | Window | Node, options?: {}) => boolean;
    mouseUp: (element: Document | Element | Window | Node, options?: {}) => boolean;
    popState: (element: Document | Element | Window | Node, options?: {}) => boolean;
    select: (element: Document | Element | Window | Node, options?: {}) => boolean;
    touchCancel: (element: Document | Element | Window | Node, options?: {}) => boolean;
    touchEnd: (element: Document | Element | Window | Node, options?: {}) => boolean;
    touchMove: (element: Document | Element | Window | Node, options?: {}) => boolean;
    touchStart: (element: Document | Element | Window | Node, options?: {}) => boolean;
    resize: (element: Document | Element | Window | Node, options?: {}) => boolean;
    scroll: (element: Document | Element | Window | Node, options?: {}) => boolean;
    wheel: (element: Document | Element | Window | Node, options?: {}) => boolean;
    abort: (element: Document | Element | Window | Node, options?: {}) => boolean;
    canPlay: (element: Document | Element | Window | Node, options?: {}) => boolean;
    canPlayThrough: (element: Document | Element | Window | Node, options?: {}) => boolean;
    durationChange: (element: Document | Element | Window | Node, options?: {}) => boolean;
    emptied: (element: Document | Element | Window | Node, options?: {}) => boolean;
    encrypted: (element: Document | Element | Window | Node, options?: {}) => boolean;
    ended: (element: Document | Element | Window | Node, options?: {}) => boolean;
    loadedData: (element: Document | Element | Window | Node, options?: {}) => boolean;
    loadedMetadata: (element: Document | Element | Window | Node, options?: {}) => boolean;
    loadStart: (element: Document | Element | Window | Node, options?: {}) => boolean;
    pause: (element: Document | Element | Window | Node, options?: {}) => boolean;
    play: (element: Document | Element | Window | Node, options?: {}) => boolean;
    playing: (element: Document | Element | Window | Node, options?: {}) => boolean;
    progress: (element: Document | Element | Window | Node, options?: {}) => boolean;
    rateChange: (element: Document | Element | Window | Node, options?: {}) => boolean;
    seeked: (element: Document | Element | Window | Node, options?: {}) => boolean;
    seeking: (element: Document | Element | Window | Node, options?: {}) => boolean;
    stalled: (element: Document | Element | Window | Node, options?: {}) => boolean;
    suspend: (element: Document | Element | Window | Node, options?: {}) => boolean;
    timeUpdate: (element: Document | Element | Window | Node, options?: {}) => boolean;
    volumeChange: (element: Document | Element | Window | Node, options?: {}) => boolean;
    waiting: (element: Document | Element | Window | Node, options?: {}) => boolean;
    load: (element: Document | Element | Window | Node, options?: {}) => boolean;
    error: (element: Document | Element | Window | Node, options?: {}) => boolean;
    animationStart: (element: Document | Element | Window | Node, options?: {}) => boolean;
    animationEnd: (element: Document | Element | Window | Node, options?: {}) => boolean;
    animationIteration: (element: Document | Element | Window | Node, options?: {}) => boolean;
    transitionCancel: (element: Document | Element | Window | Node, options?: {}) => boolean;
    transitionEnd: (element: Document | Element | Window | Node, options?: {}) => boolean;
    transitionRun: (element: Document | Element | Window | Node, options?: {}) => boolean;
    transitionStart: (element: Document | Element | Window | Node, options?: {}) => boolean;
    doubleClick: (element: Document | Element | Window | Node, options?: {}) => boolean;
    pointerOver: (element: Document | Element | Window | Node, options?: {}) => boolean;
    pointerEnter: (element: Document | Element | Window | Node, options?: {}) => boolean;
    pointerDown: (element: Document | Element | Window | Node, options?: {}) => boolean;
    pointerMove: (element: Document | Element | Window | Node, options?: {}) => boolean;
    pointerUp: (element: Document | Element | Window | Node, options?: {}) => boolean;
    pointerCancel: (element: Document | Element | Window | Node, options?: {}) => boolean;
    pointerOut: (element: Document | Element | Window | Node, options?: {}) => boolean;
    pointerLeave: (element: Document | Element | Window | Node, options?: {}) => boolean;
    gotPointerCapture: (element: Document | Element | Window | Node, options?: {}) => boolean;
    lostPointerCapture: (element: Document | Element | Window | Node, options?: {}) => boolean;
    offline: (element: Document | Element | Window | Node, options?: {}) => boolean;
    online: (element: Document | Element | Window | Node, options?: {}) => boolean;
    pageHide: (element: Document | Element | Window | Node, options?: {}) => boolean;
    pageShow: (element: Document | Element | Window | Node, options?: {}) => boolean;
};
export * from '@testing-library/react';
export { customRender as render, customFireEvent as fireEvent };
