import { DetailValue } from "./object-details.types";

export const details: DetailValue[] = [
  {
    field: "helloWorld",
    type: "string",
    description: "Lorem ipsum",
    name: "Hello world",
    value: "Lorem ipsum sit amet",
    xs: 12,
    sm: 3,
    md: 12,
  },
  {
    field: "quantity",
    type: "number",
    description: "Lorem ipsum",
    name: "Q",
    value: 1,
    xs: 12,
    sm: 3,
    md: 1,
  },
  {
    field: "status",
    type: "string",
    description: "Lorem ipsum",
    name: "Status",
    value: "Open",
    xs: 12,
    sm: 3,
  },
  {
    field: "currency",
    type: "string",
    description: "Lorem ipsum",
    name: "Unit Price Currency",
    value: "MXN",
    xs: 12,
    sm: 3,
  },
  {
    field: "tradeDate",
    type: "string",
    description: "Lorem ipsum",
    name: "Trade date",
    value: "Thu Jul 21 2022 22:44:10 GMT+0200 (Central European Summer Time)",
    xs: 12,
    sm: 3,
  },
];
