import { DetailValue } from "./object-details.types";
import { faker } from "@faker-js/faker";

export const details: DetailValue[] = [
  {
    field: "firstName",
    type: "string",
    description: "User first name",
    name: "First name",
    value: faker.name.firstName(),
    xs: 12,
    sm: 6,
    md: 4,
  },
  {
    field: "middleName",
    type: "string",
    description: "User middle name",
    name: "Middle name",
    value: faker.name.middleName(),
    xs: 12,
    sm: 6,
    md: 4,
  },
  {
    field: "lastName",
    type: "string",
    description: "User last name",
    name: "Last name",
    value: faker.name.lastName(),
    xs: 12,
    sm: 6,
    md: 4,
  },
  {
    field: "gender",
    type: "string",
    description: "User gender",
    name: "Gender",
    value: faker.name.gender(),
    xs: 12,
    sm: 6,
    md: 3,
  },
  {
    field: "age",
    type: "number",
    description: "User age",
    name: "Age",
    value: faker.datatype.number({ min: 20, max: 60 }),
    xs: 12,
    sm: 6,
    md: 3,
  },
  {
    field: "birthDate",
    type: "string",
    description: "When he was born",
    name: "Birth Date",
    value: faker.datatype.datetime().toString(),
    xs: 12,
    sm: 6,
    md: 6,
  },
  {
    field: "car",
    type: "group",
    description: "Information about the user car",
    name: "User car",
    value: [
      {
        field: "model",
        type: "string",
        description: "Lorem ipsum",
        name: "Model",
        value: faker.vehicle.model(),
        xs: 12,
        sm: 5,
      },
      {
        field: "manufacturer",
        type: "string",
        description: "Lorem ipsum",
        name: "Manufacturer",
        value: faker.vehicle.manufacturer(),
        xs: 12,
        sm: 5,
      },
      {
        field: "color",
        type: "string",
        description: "Lorem ipsum",
        name: "Color",
        value: faker.vehicle.color(),
        xs: 12,
        sm: 2,
      },
      {
        field: "type",
        type: "string",
        description: "Lorem ipsum",
        name: "Type",
        value: faker.vehicle.type(),
        xs: 12,
        sm: 3,
      },
      {
        field: "vin",
        type: "string",
        description: "Lorem ipsum",
        name: "VIN",
        value: faker.vehicle.vin(),
        xs: 12,
        sm: 5,
      },
      {
        field: "vrm",
        type: "string",
        description: "Lorem ipsum",
        name: "VRM",
        value: faker.vehicle.vrm(),
        xs: 12,
        sm: 4,
      },
    ],
  },
  {
    field: "quantity",
    type: "number",
    description: "Lorem ipsum",
    name: "Q",
    value: faker.datatype.number({ min: 1, max: 9 }),
    xs: 12,
    sm: 2,
    md: 1,
  },
  {
    field: "available",
    type: "boolean",
    description: "Lorem ipsum",
    name: "Available",
    value: true,
    xs: 12,
    sm: 2,
  },
  {
    field: "currency",
    type: "string",
    description: "Lorem ipsum",
    name: "Unit Price Currency",
    value: "MXN",
    xs: 12,
    sm: 3,
  },
  {
    field: "tradeDate",
    type: "string",
    description: "Lorem ipsum",
    name: "Trade date",
    value: "Thu Jul 21 2022 22:44:10 GMT+0200 (Central European Summer Time)",
    xs: 12,
    sm: 3,
  },
];
