export const Resources = [
  "RESOURCE_REAL_MONEY",
  "RESOURCE_GOLD",
  "RESOURCE_GOLD_SPENDING",
  "RESOURCE_BOOSTER",
  "RESOURCE_BOOSTER_SPENDING",
  "RESOURCE_FIREFLY_POWER_UP",
  "RESOURCE_FIREFLY_POWER_UP_SPENDING",
  "RESOURCE_BUTTERFLY_POINTS",
  "RESOURCE_STAR",
  "RESOURCE_STAR_SPENDING",
  "RESOURCE_NO_ADS",
  "RESOURCE_TROPHIES",
  "RESOURCE_TROPHIES_SPENDING",
  "RESOURCE_TICKET",
  "RESOURCE_TICKET_SPENDING",
  "RESOURCE_TRIVIA_TICKET",
  "RESOURCE_TRIVIA_TICKET_SPENDING",
  "RESOURCE_VIP_WHEEL_TICKET",
  "RESOURCE_VIP_WHEEL_TICKET_SPENDING",
];

export interface ResourceEntry {
  date: string;
  resource: string;
  amount: number;
  increment: number;
  category: string;
  subcategory?: string;
}
